app:
  base-url-bot: http://localhost:8090/

spring:
  application:
    name: finance
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5450/financeApp_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
    change-log: liquibase/master.xml

server:
  port: 3000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
