server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true       # Автоматически создавать маршруты для сервисов из Eureka
          lower-case-service-id: true
      routes:
        - id: finance-route
          uri: lb://finance
          predicates:
            - Path=/finance/**

        - id: tgBot-route
          uri: lb://tgBot
          predicates:
            - Path=/tg/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

