version: '3.8'

services:
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    ports:
      - "7001:6379"
      - "17001:17001"
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379"
    ]
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    ports:
      - "7002:6379"
      - "17002:17002"
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379"
    ]
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    ports:
      - "7003:6379"
      - "17003:17003"
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379"
    ]
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:7
    container_name: redis-node-4
    ports:
      - "7004:6379"
      - "17004:17004"
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379"
    ]
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:7
    container_name: redis-node-5
    ports:
      - "7005:6379"
      - "17005:17005"
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379"
    ]
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:7
    container_name: redis-node-6
    ports:
      - "7006:6379"
      - "17006:17006"
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379"
    ]
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
