services:
  postgresql:
    image: postgres:16
    ports:
      - "5450:5432"
    environment:
      POSTGRES_DB: financeApp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://localhost:5432/financeApp_db
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog/
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
