version: '3.8'

services:
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379",
      "--cluster-announce-ip", "redis-node-1",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379",
      "--maxmemory", "100mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379",
      "--cluster-announce-ip", "redis-node-2",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379",
      "--maxmemory", "100mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379",
      "--cluster-announce-ip", "redis-node-3",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379",
      "--maxmemory", "100mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:7
    container_name: redis-node-4
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379",
      "--cluster-announce-ip", "redis-node-4",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379",
      "--maxmemory", "100mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:7
    container_name: redis-node-5
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379",
      "--cluster-announce-ip", "redis-node-5",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379",
      "--maxmemory", "100mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:7
    container_name: redis-node-6
    command: [
      "redis-server",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--bind", "0.0.0.0",
      "--protected-mode", "no",
      "--port", "6379",
      "--cluster-announce-ip", "redis-node-6",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379",
      "--maxmemory", "100mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
