FROM eclipse-temurin:21-jdk AS builder

WORKDIR app

ARG JAR_FILE=finance/target/finance.jar

COPY ${JAR_FILE} app.jar

RUN java -Djarmode=layertools -jar app.jar extract


FROM eclipse-temurin:21-jdk

WORKDIR app

COPY --from=builder app/spring-boot-loader/ ./
COPY --from=builder app/dependencies/ ./
COPY --from=builder app/snapshot-dependencies/ ./
COPY --from=builder app/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
#docker run -d --name finance-app --network financeapp_backend -p 8085:3000 finance-app