FROM maven:3.9.6-eclipse-temurin-21

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/W4NTER/starter_t1.git /build/starter_t1

WORKDIR /build/starter_t1
RUN mvn clean install -DskipTests

WORKDIR /build/app

COPY . .

RUN mvn dependency:go-offline -B