FROM maven:3.9.6-eclipse-temurin-21 AS builder

COPY . /build/app
WORKDIR /build/app

RUN mvn clean package -pl discovery-service -am -DskipTests -X

FROM eclipse-temurin:21-jre AS runtime

WORKDIR /app

COPY --from=builder /build/app/discovery-service/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

#docker run -d --name discovery-service-app --network financeapp_backend -p port:port discovery-service-app