FROM eclipse-temurin:21-jdk AS builder

WORKDIR app

ARG JAR_FILE=gateway-service/target/gateway-service-0.1.jar

COPY ${JAR_FILE} app.jar

RUN java -Djarmode=layertools -jar app.jar extract


FROM eclipse-temurin:21-jdk

WORKDIR app

COPY --from=builder app/spring-boot-loader/ ./
COPY --from=builder app/dependencies/ ./
COPY --from=builder app/snapshot-dependencies/ ./
COPY --from=builder app/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
#docker run -d --name gateway-service-app --network financeapp_backend -p port:port gateway-service-app