app:
  base-url-bot: http://localhost:8090

spring:
  application:
    name: finance
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5450/financeApp_db
  liquibase:
    enabled: false
    change-log: liquibase/master.xml

server:
  port: 3000
