name: Finance Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/finance.yml
      - finance/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      packages: write

    steps:
      #Качаем основной репозиторий
      - name: Checkout main project
        uses: actions/checkout@v4
        with:
          path: main

      #Качаем стартер в отдельную папку
      - name: Checkout starter
        uses: actions/checkout@v3
        with:
          repository: W4NTER/starter_t1
          path: starter

#      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install starter locally
        run: |
          cd starter_t1
          mvn install

      - name: maven build
        run: mvn -pl finance -am package

      - id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/finance/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - run: mvn -pl finance -am checkstyle:check

  integration-test:
    name: integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - run: mvn -pl finance -am verify -Dskip.unit.tests=true
